blueprintId: birman-banking

services:
  - type: web
    name: birman-banking-server
    env: docker
    plan: free
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: birman-banking-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: birman-banking-server
          envVarKey: RENDER_EXTERNAL_URL
